FROM php:7.0-fpm

COPY sources.list /etc/apt/

RUN docker-php-ext-install pdo_mysql

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

RUN pecl install memcache-4.0.5.2 \
    && docker-php-ext-enable memcache

RUN pecl install xdebug-2.6.1 \
    && docker-php-ext-enable xdebug
COPY ./conf.d/* /usr/local/etc/php/conf.d